### ISSUE TITLE
Input elements should not have cursor:pointer

### ISSUE THREAD

**Issue by pichfl** [darlanrod/input-range-sass#10]
`cursor:pointer;` should be reserved for links and link-like elements only. As module can be seen as an implementation of best practices, I would recommend to switch to `cursor:default`, which would be the most appropriate choice. 

I can provide a PR, but I'm about to leave the office right now, will check this issue later.

**Comment by darlanrod** [comment]
Thanks, @pichfl ! Done!

**Comment by pichfl** [comment]
So much for me coming back for this 😅 Thanks a lot! We still use this in our projects and I'm glad to see it still going.
