### ISSUE TITLE
Vertical option

### ISSUE THREAD

**Issue by herrKlein** [darlanrod/input-range-sass#15]
Could you create a cross browser vertical option ?

**Comment by darlanrod** [comment]
Hello, @herrKlein !

The HTML specification recommends that browsers automatically switch to drawing range controls vertically if the specified width is less than the height. Unfortunately, no major browsers currently support vertical range controls directly. You can, however, create a vertical range control by drawing a horizontal range control on its side. The easiest way is to use CSS: by applying a transform to rotate the element, you can make it vertical.

Check out the [MDN instructions for vertical input range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/range#Change_the_orientation).
