### ISSUE TITLE
Track width webkit/moz inconsistency

### ISSUE THREAD

**Issue by hyvyys** [darlanrod/input-range-sass#16]
I see that this issue is addresed by the following:

```
&::-moz-range-track {
  height: $track-height / 2;
}
```

However applying tweaks to the variables reveals that this is not a perfect solution as with different $track-width and $track-border-width values the overall widths of the track diverge. I suggest this works better (instead of the rule above):

```
&::-moz-range-track {
  box-sizing: border-box;
}
```

**Comment by hyvyys** [comment]
Exactly the same could be applied to the thumb instead of the adjustment mixin parameter.

**Comment by darlanrod** [comment]
Thanks, @hyvyys ! Improvement applied, check out the repository.
