### ISSUE TITLE
[Question] Rotating the thumb

### ISSUE THREAD

**Issue by petrakow** [darlanrod/input-range-sass#18]
Hey, 
I have some special styling for the thumb, where it needs to be a diamond shaped thumb.

I added a  `transform: rotate(45deg);` to the thumbs, but in IE11 it cuts off the edges.
Do you have an idea how to fix this? Or probably a different solution?

**Comment by darlanrod** [comment]
Hello, André. Did you try some polyfills like https://modernizr.com/ ? Could you share the code with us?

**Comment by darlanrod** [comment]
Well, @petrakow, if you still have this problem. Open the issue again.
