### ISSUE TITLE
How to add filled part?

### ISSUE THREAD

**Issue by ddtch** [darlanrod/input-range-sass#19]
Hello, any ideas on how to add custom filled part in the left part of the slider? like on screenshot has IE in default.

**Comment by darlanrod** [comment]
Hello, David.

There is a [specification](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress) for it in Mozilla Firefox, but unfortunately for Google Chrome, Apple Safari and the new Microsoft Edge, it isn't. For Microsoft Internet Explorer and older Edge, there is a [specification](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-fill-lower), but now Edge is using the same engine of Google Chrome.

If you discover any other way to achieve this using the native properties of each browser, please let me know!

**Comment by palomamtnez** [comment]
I made use of this repo in my existing Vue component. 

In case you are using Vue, it  makes it really easy to add colour to the progress bar 😀  all I did was this:

Add this to the `[type='range']` selector:

```	
        border-radius: 16px;
	height: 7px;
```

Changed the colours to your preference, but the most important was the track colour which is now transparent (as the background colour will be dynamic using Vue, as mentioned):

```	
        $track-color: transparent !default;
```

Result of the colours are now:

```
$track-color: transparent !default;
$progress-color: #F28000 !default;
$thumb-color: #F28000 !default;

$thumb-radius: 12px !default;
$thumb-height: 24px !default;
$thumb-width: 24px !default;
$thumb-shadow-size: 0px !default;
$thumb-shadow-blur: 0px !default;
$thumb-shadow-color: $thumb-color !default;
$thumb-border-width: 0px !default;
$thumb-border-color: $thumb-color !default;

$track-width: 100% !default;
$track-height: 8px !default;
$track-shadow-size: 0px !default;
$track-shadow-blur: 0px !default;
$track-shadow-color: $track-color !default;
$track-border-width: 0px !default;
$track-border-color: $track-color !default;

$track-radius: 5px !default;
$contrast: 5% !default;

$ie-bottom-track-color: $track-color !default;`
```

To finalize, add the dynamic background on Vue:

```
 <input type="range" min="0" max="100" step="1" v-model="slider.percentage"
                           @input="myFunction()"
                           :style="{ background: 'linear-gradient(to right, #F28000 0%, #F28000 '+slider.percentage +'%, #4D2712 ' + slider.percentage + '%, #4D2712 100%)'}">
```
                    
                    
Result:

![Screen Shot 2021-09-23 at 1 38 52 PM](https://user-images.githubusercontent.com/13962572/134443142-b10629bb-0c41-44e8-822b-0eeda324c702.png)
