### ISSUE TITLE
Vertical slider. Track height in percentage.

### ISSUE THREAD

**Issue by johnhult** [darlanrod/input-range-sass#2]
If you want a slider that is supposed to be displayed vertically you get incompatible units (% and px) if you set the height to 100%.

**Comment by darlanrod** [comment]
Hi John! Thanks for the warning, but currently there is no standard for implementation of the vertical range. Mike Taylor talks about this in his article on Dev.Opera...

> The HTML Standard mentions “determin[ing] the orientation of the control from the ratio of the style-sheet-specified height and width properties.” So as long as you define the width to be smaller than the height, your browser should create a vertical range input for you... Unfortunately, Opera is still the only browser to support this out of the box. Webkit-based browsers can get by with the -webkit-appearance: slider-vertical non-standard CSS, but that doesn’t help Firefox or IE10.

The idea here was just to make the Sass version of the technique applied in the original article, but if I ever turn this into an actual component, I'll have your warning in mind. Thank you!
