### ISSUE TITLE
Question: Sliders of different colors in single page

### ISSUE THREAD

**Issue by amdp** [darlanrod/input-range-sass#20]
Hi, is there a way to make the sliders of different colors in the same page?

.sliderblue {
track-color: blue;
}
.slideryellow {
track-color: yellow;
}

does not work independently from adding the @import or @use or inserting the full scss code in the main css file. Adding !global in the class changes the color but also  previous ones.

**Comment by amdp** [comment]
Yes, you should just use the !global flag after the variable in the class:

.sliderblue {
track-color: blue !global;
}

**Comment by darlanrod** [comment]
Yes. You can use the properties within separated classes/ids in your style or override only the properties you want to inline in the page element.

**Comment by amdp** [comment]
I guess that is what I did but it is not working.
I quoted what I did in the above comment.

**Comment by darlanrod** [comment]
Yes, but you are doing it wrong. There is no property in CSS called `track-color` that you are using. You need to override all properties that use the `$track-color` variable in SCSS for it to work properly.

**Comment by amdp** [comment]
Oh I just mistyped it here as per an example, the code is this:

``
  $track-color: #00F;
  $thumb-color: #00F;
  .sliderD{
    $track-color: #000;
    $thumb-color: #000;
  }
  .sliderU{
    $track-color: #FF0;
    $thumb-color: #FF0;
  }
``

and the class is not having effect here:
``
<input
            v-model="formSlider"
            type="range"
            class="mb-4 sliderD"
            min="0.01"
            max="0.99"
            step="0.01"
          />
``
the slider is still blue (#00F)

**Comment by darlanrod** [comment]
I recommend that you use Mixin (https://sass-lang.com/documentation/at-rules/mixin) or Extend (https://sass-lang.com/documentation/at-rules/extend) to accomplish this.

**Comment by amdp** [comment]
All the examples in the documentation you provided seem to work with local variables, while it seems like what is needed is to change locally the global variable $track-color or any equivalent of it, and it doesn't seem to be possible when it becomes local... am I wrong?

**Comment by darlanrod** [comment]
I created an example of how you can customize your slides: https://gist.github.com/darlanrod/fedf476c3d22f2b842ed26da7c943451

Enjoy.

**Comment by amdp** [comment]
Mixing your two suggestions I found a way to make it shorter:
```

$contrast 5%; //to be defined if not using https://github.com/darlanrod/input-range-scss
@mixin colorslider($track-colors) {
    $ie-bottom-track-colors: darken($track-colors, $contrast) !default;
    &:focus {
      &::-webkit-slider-runnable-track {
        background: lighten($track-colors, $contrast);
      }
      &::-ms-fill-lower {
        background: $track-colors;
      }
      &::-ms-fill-upper {
        background: lighten($track-colors, $contrast);
      }
    }
    &::-webkit-slider-runnable-track {
      background: $track-colors;
    }
    &::-moz-range-track {
      background: $track-colors;
    }
    &::-ms-fill-lower {
      background: $ie-bottom-track-colors;
    }
    &::-ms-fill-upper {
      background: $track-colors;
    }
  }

  .slideOne {
    @include colorslider(#F00)
  }

  .slideTwo {
    @include colorslider(#00F)
  }
```
