### ISSUE TITLE
Using "/" in Sass is deprecated; use math.div instead

### ISSUE THREAD

**Issue by toBeOfUse** [darlanrod/input-range-sass#21]
Hello, according to [this](https://sass-lang.com/documentation/breaking-changes/slash-div) using the slash as the division operator is not supposed to be done in Sass anymore and will eventually break, and when I use your package Webpack issues many deprecation warnings about it. Since this is a very straightforward problem, I made the relevant changes to my own fork and will open a pull request for it.

**Comment by darlanrod** [comment]
Thanks @toBeOfUse! `math.div` implemented.
