### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by lazarljubenovic** [darlanrod/input-range-sass#4]
Are there any plans to turn this into a simple npm package? Or it's already there and I'm missing it?

**Comment by darlanrod** [comment]
It is a good idea @lazarljubenovic . I'll do it soon and tell you. Thank you!

**Comment by darlanrod** [comment]
@lazarljubenovic, i finally published the NPM package.

`npm install --save input-range-scss`

Enjoy!
